#!/bin/bash

RELEASE_VER=5.0
POI_IMAGE="${POI_IMAGE:-photon/installer}"

fail() {
    echo "$1"
    exit 1
}

build_iso() {

    params=()
    for p in "${ISO_PARAMS[@]}" ; do
        params+=("--param")
        params+=("$p")
    done
    for p in "${COMMON_PARAMS[@]}" ; do
        params+=("--param")
        params+=("$p")
    done

    volumes=()
    for v in "${VOLUMES[@]}" ; do
        volumes+=("-v")
        volumes+=("$v")
    done

    echo "running 'photon-iso-builder'"
    { [ ${#params[@]} -gt 0 ] && printf "%s\0" "${params[@]}" ; } | xargs -t -0 \
        docker run --rm --privileged \
        -v /dev:/dev \
        -v $(pwd):/workdir \
        "${volumes[@]}" \
        --network=host \
        ${POI_IMAGE} \
        photon-iso-builder --config ${ISO_CFG_FILE} -v ${RELEASE_VER} || fail "'photon-iso-builder' failed with $?"
    echo "done with 'photon-iso-builder'"
}

usage() {
    echo "Usage: $0"
    echo "          [--iso-config <config-file>] iso config file that describes the ISO image (required)"
    echo "          [--iso-param <key=value>] set parameters in the iso config (optional, can be given multiple times)"
    echo "          [--param <key=value>] set parameters in the iso config (optional, can be given multiple times)"
    echo "          [--poi-image] docker image to use. Default: ${POI_IMAGE}"
    echo "          [--step] optional - build steps to do, currently only 'iso'. Can be given multiple times."
    echo "          [-v|--releasever <version>] (Photon release version, default is ${RELEASE_VER})"
    echo "          [--volume src:dst] additional volumes to be mounted to the docker container"
}

OPTS=$(getopt -o hv: --long iso-config:,iso-param:,param:,poi-image:,releasever:,step:,volume: -n $0 -- "$@")
if [ $? != 0 ] ; then
    usage
    echo "Terminating." >&2
    exit 1
fi

eval set -- "$OPTS"

while true; do
    case "$1" in
        -h)                 usage ; exit 0;;
        --iso-config)       ISO_CFG_FILE=${2} ; shift 2 ;;
        --iso-param)        ISO_PARAMS+=("${2}"); shift 2 ;;
        --poi-image)        POI_IMAGE=${2} ; shift 2 ;;
        --step)             STEPS+=("${2}"); shift 2 ;;
        -v | --releasever)  RELEASE_VER=${2} ; shift 2 ;;
        --param)            COMMON_PARAMS+=("${2}"); shift 2 ;;
        --volume)           VOLUMES+=("${2}"); shift 2 ;;
        --) shift; break ;;
        *) break ;;
    esac
done

if [ ${#STEPS[@]} -eq 0 ]; then
    STEPS=("iso")
fi

for step in "${STEPS[@]}" ; do
    case "$step" in
        iso)  build_iso || exit 1 ;;
        *)    echo "unknown step $step" >&2 ; exit 1 ;;
    esac
done
