#!/bin/bash

RELEASE_VER=5.0

create_repo()
{
    tdnf install -y --releasever=${RELEASE_VER} --alldeps --downloadonly --downloaddir=/repo $(poi-pkglist -c${CFG_FILE})
    pushd /repo || exit 1
    createrepo .
    popd || exit 1
}

usage() {
    echo "Usage: $0"
    echo "          [-c|--config <config-file>] (required)"
    echo "          [-v|--releasever <version>] (default is ${RELEASE_VER})"
    echo "          [--repo-paths] (default ${REPO_PATHS})"
}

OPTS=$(getopt -o hc:v: --long config:,releasever:,repo-paths: -n $0 -- "$@")
if [ $? != 0 ] ; then
    usage
    echo "Terminating." >&2
    exit 1
fi

eval set -- "$OPTS"

while true; do
    case "$1" in
        -h) usage ; exit 0;;
        -c | --config) CFG_FILE=${2} ; shift 2 ;;
        -v | --releasever) RELEASE_VER=${2} ; shift 2 ;;
        --repo-paths) REPO_PATHS=${2} ; shift 2 ;;
        --) shift; break ;;
        *) break ;;
    esac
done

if [ -z "${CFG_FILE}" ] ; then
    echo "need a config file" >&2
    usage
    echo "Terminating." >&2
    exit 1
fi

create_repo
